--Script made by green ghost#4841 | https://github.com/greenghost110
--Licenced under GPLv3

--By using this script you acknowledge you could get banned. 
--I suggest using an alternitive account.
--If you understand, change false to true under this line
local EULA = false



--Don't touch anything below if you don't understand coding!

local chatrem = game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest
if EULA == true then
chatrem:FireServer('The State of Florida has asked us to', "All")
wait(3)
chatrem:FireServer('Disclose our ***** crimes to you', "All")
wait(3)
chatrem:FireServer('We were bad, but now we are good', "All")
wait(3)
chatrem:FireServer('We are moving into your neighborhood', "All")
wait(3)
chatrem:FireServer('You know were trying our best to be', "All")
wait(3)
chatrem:FireServer('Functioning members of society', "All")
wait(3)
chatrem:FireServer('We are not here to start no trouble', "All")
wait(3)
chatrem:FireServer('We are legally required to do the *** offender shuffle', "All")
wait(3)
chatrem:FireServer('I am Larry and I will refrain', "All")
wait(3)
chatrem:FireServer('From touching my neighbors kids again', "All")
wait(3)
chatrem:FireServer('What I did was not too kind', "All")
wait(3)
chatrem:FireServer('But I am a nice guy, you will come to find', "All")
wait(3)
chatrem:FireServer('I have a backyard and a real nice pool', "All")
wait(3)
chatrem:FireServer('You all should come over for a BBQ', "All")
wait(3)
chatrem:FireServer('We could make some cold drinks in my blender', "All")
wait(3)
chatrem:FireServer('But do keep in mind I am a *** offender', "All")
wait(3)
chatrem:FireServer('Vernon is my name', "All")
wait(3)
chatrem:FireServer('My battery arrest is what bought me fame', "All")
wait(3)
chatrem:FireServer('But there is much more to know about me', "All")
wait(3)
chatrem:FireServer('I love to dance, and I love to ski', "All")
wait(3)
chatrem:FireServer('I zip and zoom on through the snow', "All")
wait(3)
chatrem:FireServer('Just strap on my boots and watch me go', "All")
wait(3)
chatrem:FireServer('But I cannot ski until December', "All")
wait(3)
chatrem:FireServer('Till then I am just a *** offender', "All")
wait(3)
chatrem:FireServer('I am Charles Dolling, dropping rhymes', "All")
wait(3)
chatrem:FireServer('Ive been arrested seven times', "All")
wait(3)
chatrem:FireServer('I know that sounds like a lot', "All")
wait(3)
chatrem:FireServer('But three of those times were for vandalism', "All")
wait(3)
chatrem:FireServer('I feel real bad, I got caught', "All")
wait(3)
chatrem:FireServer('I might do it again, probably not', "All")
wait(3)
chatrem:FireServer('I am not here to make pretenses', "All")
wait(3)
chatrem:FireServer('I am here because of my *** offenses', "All")
wait(3)
chatrem:FireServer('I am Sam, I am number one', "All")
wait(3)
chatrem:FireServer('Apologizing for what I have done', "All")
wait(3)
chatrem:FireServer('Case you are wondering what that was', "All")
wait(3)
chatrem:FireServer('I snuck into a bath room and I fisted my cuz', "All")
wait(3)
chatrem:FireServer('I held her down and watched her struggle', "All")
wait(3)
chatrem:FireServer('Then played with her melons because I like to juggle', "All")
wait(3)
chatrem:FireServer('I am not here to eat those truffles', "All")
wait(3)
chatrem:FireServer('I am  just here to do the *** offender shuffle', "All")
wait(3)
chatrem:FireServer('Hey everybody I am Laura', "All")
wait(3)
chatrem:FireServer('Proving that girls can do it too', "All")
wait(3)
chatrem:FireServer('And by it I mean touch your cousin', "All")
wait(3)
chatrem:FireServer('Was it worth it? No, it was not.', "All")
wait(3)
chatrem:FireServer('You will not find me in your childs play set', "All")
wait(3)
chatrem:FireServer('Cause I gotta wear this ankle bracelet', "All")
wait(3)
chatrem:FireServer('I am not here to go on a ******', "All")
wait(3)
chatrem:FireServer('I am here because I am a *** offender', "All")
wait(3)
chatrem:FireServer('Marc is my name', "All")
wait(3)
chatrem:FireServer('I am moving in somewhere on your block', "All")
wait(3)
chatrem:FireServer('Not in a house, but in a van', "All")
wait(3)
chatrem:FireServer('If you need me to move it, I sure can', "All")
wait(3)
chatrem:FireServer('The last thing I want is any trouble', "All")
wait(3)
chatrem:FireServer('I learned my lesson from the *** offender shuffle', "All")
wait(3)
chatrem:FireServer('I am the one they call Arthur', "All")
wait(3)
chatrem:FireServer('They said I didnt have to show my face', "All")
wait(3)
chatrem:FireServer('My first trial ended in a hung jury', "All")
wait(3)
chatrem:FireServer('If I am found guilty they will unblur me', "All")
wait(3)
chatrem:FireServer('I am not the necrophiliac Arthur', "All")
wait(3)
chatrem:FireServer('Thats a different Arthur', "All")
wait(3)
chatrem:FireServer('I am not here to be my own defender', "All")
wait(3)
chatrem:FireServer('I am here because I am possibly a *** offender', "All")
wait(3)
chatrem:FireServer('Okay real quick, I-I am not like these people, okay?', "All")
wait(3)
chatrem:FireServer('This is an extortion plot by my ex, who is the only witness, and shes trying to take away my kids and if...', "All")
wait(3)
chatrem:FireServer('*police officer pulls gun*', "All")
wait(3)
chatrem:FireServer('I am not here to pack my duffel', "All")
wait(3)
chatrem:FireServer('I am just here to do the *** offender shuffle', "All")
wait(3)
chatrem:FireServer('The State of Florida has asked us to', "All")
wait(3)
chatrem:FireServer('Disclose our ***** crimes to you', "All")
wait(3)
chatrem:FireServer('We were bad, but now we are good', "All")
wait(3)
chatrem:FireServer('We are moving into your neighborhood', "All")
wait(3)
chatrem:FireServer('We are obliged to admit', "All")
wait(3)
chatrem:FireServer('The crimes of which we were convicted', "All")
wait(3)
chatrem:FireServer('We are not here to start no trouble', "All")
wait(3)
chatrem:FireServer('We are legally required to do the *** offender shuffle', "All")
wait(3)
end
